export const metadata={title:'Terms of Use — Midi CoPilot'};
const S=({n,t,children})=><><h2>{n}. {t}</h2><p>{children}</p></>;
export default function Terms(){return <main className="legal"><a className="brand" href="/">Midi CoPilot</a><div className="legalHead"><div className="kicker">LEGAL</div><h1>Terms of Use</h1><p>Effective September 26, 2026</p></div><div className="legalBody"><p className="legalNotice"><b>Launch draft:</b> This is general terms language, not legal advice. Before release, have qualified counsel review it and replace the bracketed company/contact/jurisdiction details.</p>
<S n="1" t="Acceptance">By downloading, installing, accessing, or using Midi CoPilot, Midi CoPilot Link, or related websites and services (the “Services”), you agree to these Terms. If you do not agree, do not use the Services.</S>
<S n="2" t="License">Subject to these Terms and applicable marketplace rules, [LEGAL COMPANY NAME] grants you a limited, non-exclusive, non-transferable, revocable license to use the Services for lawful purposes. You may not resell, sublicense, circumvent security, or reverse engineer the Services except where applicable law expressly permits it.</S>
<S n="3" t="Pricing and Purchases">Midi CoPilot is currently intended as a one-time $4.99 purchase per user with no subscription. Midi CoPilot Link for the host Mac is intended to be available at no additional charge. Actual store pricing, taxes, availability, refunds, and transaction terms may vary by region and platform.</S>
<S n="4" t="Wireless, Network, MIDI, and Cue Reliability">The Services depend on systems that may include Wi-Fi, Bluetooth, local networks, MIDI, Apple devices and operating systems, third-party software, hardware, network equipment, radio conditions, and other components outside our control. We do not guarantee that a MIDI message, cue, control change, program change, transport command, or other instruction will be transmitted, received, interpreted, or executed without delay, duplication, interruption, incompatibility, or failure.</S>
<S n="5" t="Live Production and Critical-Use Warning">Midi CoPilot is a production-control convenience and must not be relied upon as the sole control mechanism for safety-critical, emergency, life-safety, medical, security, industrial, or other mission-critical functions. Users are responsible for testing configurations before use and maintaining appropriate backup control methods for concerts, worship services, theatrical performances, broadcasts, presentations, live productions, and other events.</S>
<S n="6" t="Third-Party Systems">References to third-party products are descriptive and do not imply affiliation, endorsement, or guaranteed compatibility. Third-party products may change without notice. You are responsible for confirming that your intended hardware, software, MIDI implementation, and configuration work as required before a production.</S>
<S n="7" t="User Responsibility">You are responsible for device approval, MIDI mappings, cue assignments, network configuration, testing, security, backups, operator training, and determining whether the Services are appropriate for a particular use. Do not use the Services where an incorrect or failed command could create an unreasonable risk of injury, property damage, or other harm.</S>
<S n="8" t="Disclaimer of Warranties">TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICES ARE PROVIDED “AS IS” AND “AS AVAILABLE,” WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, AVAILABILITY, ACCURACY, RELIABILITY, OR ERROR-FREE OPERATION. SOME JURISDICTIONS DO NOT ALLOW CERTAIN EXCLUSIONS.</S>
<S n="9" t="Limitation of Liability">TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, [LEGAL COMPANY NAME] AND ITS OWNERS, DEVELOPERS, AFFILIATES, EMPLOYEES, CONTRACTORS, AND AGENTS WILL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, OR FOR LOST PROFITS, LOST REVENUE, LOST DATA, MISSED OR INCORRECT CUES, INTERRUPTED PERFORMANCES, PRODUCTION DELAYS, BUSINESS INTERRUPTION, LOSS OF GOODWILL, OR EQUIPMENT DAMAGE ARISING FROM USE OF OR INABILITY TO USE THE SERVICES. TO THE MAXIMUM EXTENT PERMITTED BY LAW, AGGREGATE LIABILITY WILL NOT EXCEED THE GREATER OF THE AMOUNT YOU PAID FOR THE AFFECTED SERVICE OR THE MINIMUM LIABILITY REQUIRED BY APPLICABLE LAW. Nothing excludes liability that cannot lawfully be excluded or limited.</S>
<S n="10" t="Indemnification">To the extent permitted by law, you agree to defend, indemnify, and hold harmless [LEGAL COMPANY NAME] and its owners, developers, affiliates, employees, contractors, and agents from third-party claims, liabilities, damages, losses, and reasonable costs arising from unlawful use of the Services, violation of these Terms, or configuration or operation that causes harm.</S>
<S n="11" t="Intellectual Property">The Services, software, interfaces, branding, graphics, text, and original materials are owned by [LEGAL COMPANY NAME] or its licensors and protected by applicable intellectual-property laws. Third-party names and marks belong to their respective owners.</S>
<S n="12" t="Updates and Availability">We may update, modify, suspend, or discontinue features. Changes to operating systems, networks, MIDI implementations, or third-party products may affect compatibility. We do not promise perpetual compatibility with every product or operating-system version.</S>
<S n="13" t="Termination">We may suspend or terminate access where reasonably necessary to address unlawful use, security risks, abuse, or violations of these Terms, subject to applicable law and marketplace requirements.</S>
<S n="14" t="Apple and Marketplace Terms">If you obtain Midi CoPilot through the Apple App Store, your use is also subject to applicable Apple Media Services terms and App Store rules. Any provisions required by the applicable marketplace are incorporated to the extent required.</S>
<S n="15" t="Governing Law and Disputes">These Terms will be governed by the laws of [STATE/JURISDICTION], without regard to conflict-of-law rules, except where consumer law requires otherwise. Venue and any dispute-resolution procedure should be finalized with counsel before launch.</S>
<S n="16" t="Severability and Entire Agreement">If a provision is unenforceable, the remaining provisions remain in effect to the extent permitted by law. These Terms, together with incorporated policies, form the agreement governing use of the Services.</S>
<S n="17" t="Changes to These Terms">We may update these Terms from time to time. The effective date above will be updated when changes are published. Where required by law, additional notice will be provided.</S>
<S n="18" t="Contact">Questions about these Terms may be sent to [SUPPORT/LEGAL EMAIL] or [LEGAL COMPANY ADDRESS].</S>
<a className="legalBack" href="/">← Back to Midi CoPilot</a></div></main>}
