'use client';
import {useEffect,useState} from 'react';
const colors=['#4A87FF','#996BFF','#FF61A8','#FF4D4D','#FF8F3D','#FFD638','#33D678','#33CCC2','#4A87FF','#996BFF','#FF61A8','#FF4D4D'];
export default function Home(){
 const [active,setActive]=useState(3); const [pulse,setPulse]=useState(false);
 const fire=(n)=>{setActive(n);setPulse(false);requestAnimationFrame(()=>setPulse(true));setTimeout(()=>setPulse(false),900)};
 useEffect(()=>{const id=setInterval(()=>fire((Math.floor(Math.random()*12)+1)),4200);return()=>clearInterval(id)},[]);
 return <main>
 <nav><a className="brand" href="#top">Midi CoPilot</a><div className="navlinks"><a href="#how">How it works</a><a href="#features">Features</a><a href="#link">CoPilot Link</a><a className="pill" href="#download">Get the app</a></div></nav>
 <section id="top" className="hero"><div className="eyebrow"><span/>CONNECTED · SHOW READY</div><h1>Your whole show.<br/><em>One tap away.</em></h1><p>Wireless MIDI cue control for the stage. Fire tracks, cues and transport commands from iPhone or iPad—instantly.</p><div className="actions"><a className="primary" href="#download">Get Midi CoPilot</a><a className="secondary" href="#live-demo">Try the cue demo</a></div>
 <div className="heroSystem"><div className="device"><div className="deviceGlow"/><img src="/app-main.png" alt="Midi CoPilot cue interface"/></div><div className={`signal ${pulse?'go':''}`}><span/><span/><span/><b>MIDI</b></div><div className="mac"><div className="macTop"><i/><span>Midi CoPilot Link</span><em>● Connected</em></div><div className="macBody"><small>INCOMING COMMAND</small><strong>CC {19+active}</strong><p>Cue {active} · Channel 1 · Value 127</p><div className="meter"><i/></div></div></div></div>
 <div className="trust">Built for worship teams · bands · production crews</div></section>
 <section id="how" className="story"><div className="kicker">FROM TAP TO SHOW</div><h2>Your laptop can stay<br/>where it belongs.</h2><p className="lede">Midi CoPilot turns the device already in your hand into a stage-ready wireless cue controller.</p><div className="flow"><div><b>01</b><h3>Tap</h3><p>Hit a large, color-coded cue from anywhere on stage.</p></div><i>→</i><div><b>02</b><h3>Send</h3><p>Your command travels wirelessly to Midi CoPilot Link on your Mac.</p></div><i>→</i><div><b>03</b><h3>Fire</h3><p>Link passes MIDI straight to your show software.</p></div></div><div className="software"><span>Ableton Live</span><span>Logic Pro</span><span>MainStage</span><span>ProPresenter</span><span>Any MIDI destination</span></div></section>
 <section id="live-demo" className="demo"><div className="demoCopy"><div className="kicker">INTERACTIVE DEMO</div><h2>Built for the moment<br/>you can't miss.</h2><p>Tap a cue. The pad fires instantly and every connected device can follow the current cue.</p><div className="status"><span/> Cue {active} fired · YOU</div><div className="midiReadout"><small>OUTGOING MIDI</small><b>CC {19+active}</b><span>CH 1 · 127</span></div></div><div className="grid">{colors.map((c,i)=><button key={i} onClick={()=>fire(i+1)} style={{'--c':c}} className={active===i+1?'active':''}><span>{i+1}</span>Cue {i+1}</button>)}</div></section>
 <section id="features" className="features"><div className="kicker">STAGE READY</div><h2>Simple at rehearsal.<br/>Serious at showtime.</h2><div className="featuregrid"><article><strong>64</strong><h3>Cues on iPad</h3><p>Up to 24 on iPhone and an 8 × 8 grid on iPad, portrait or landscape.</p></article><article><strong>↻</strong><h3>Always connected</h3><p>Rock-solid Wi‑Fi with auto-reconnect and Bluetooth backup.</p></article><article><strong>●</strong><h3>Everyone stays in sync</h3><p>Every connected device highlights the current cue and shows who fired it.</p></article><article><strong>⌁</strong><h3>Showtime lock</h3><p>Approve devices on the Mac, then lock the system down when the show starts.</p></article></div></section>
 <section id="link" className="linkSection"><div className="linkWindow"><div className="windowBar"><i/><i/><i/><span>Midi CoPilot Link</span></div><div className="linkInner"><div><small>APPROVED DEVICES</small><p><b>●</b> Stage iPhone <em>Connected</em></p><p><b>●</b> Worship iPad <em>Connected</em></p></div><div><small>MIDI OUTPUT</small><h3>Network Session 1</h3><p className="locked">⌁ SHOWTIME LOCK · ON</p></div></div></div><div className="linkCopy"><div className="kicker">THE MAC COMPANION</div><h2>Meet CoPilot Link.</h2><p>Your Mac receives every tap and passes it straight to MIDI. Approve devices before the show, lock things down at showtime, and keep your performance system where it belongs.</p><div className="miniFeatures"><span>Device approval</span><span>Auto reconnect</span><span>Bluetooth backup</span><span>Showtime Lock</span></div></div></section>
 <section className="screens"><div><div className="kicker">MAKE IT YOURS</div><h2>Your cues.<br/>Your colors.<br/>Your show.</h2><p>Name every cue, assign MIDI CC values, choose press and release behavior, and map dedicated Play and Stop controls.</p></div><div className="stack"><img src="/app-cues.png" alt="Cue setup"/><img src="/app-settings.png" alt="MIDI settings"/></div></section>
 <section id="download" className="cta"><div className="brand big">Midi CoPilot</div><h2>Leave the laptop.<br/>Run the show.</h2><p>Wireless MIDI cue control for iPhone and iPad.</p><div className="actions center"><a className="primary" href="#">App Store — Coming Soon</a><a className="secondary" href="#link">Midi CoPilot Link for Mac</a></div></section>
 <footer><div className="brand">Midi CoPilot</div><p>Your whole show, one tap away.</p><div className="footerlinks"><a href="#">Support</a><a href="#">Privacy</a></div><small>© 2026 Midi CoPilot</small></footer>
 </main>}
